In [136]:
!pip3 install -U ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\afiat_trading\anaconda3\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\afiat_trading\anaconda3\lib\site-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\afiat_trading\anaconda3\lib\site-packages (from ucimlrepo) (2024.12.14)
Requirement already satisfied: numpy>=1.26.0 in c:\users\afiat_trading\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\afiat_trading\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\afiat_trading\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\afiat_trading\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\afiat_trading\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)

# **1. Exploratory Data Analysis (EDA)**

**1. Import Dependencies**

In [137]:
from ucimlrepo import fetch_ucirepo 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn import metrics
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.neural_network import MLPClassifier

import pickle
from sklearn.ensemble import RandomForestClassifier
import joblib

**2. Load the Dataset**

In [138]:

# fetch dataset 
cdc_diabetes_health_indicators = fetch_ucirepo(id=891)

In [139]:
# data (as pandas dataframes) 
X = cdc_diabetes_health_indicators.data.features 
y = cdc_diabetes_health_indicators.data.targets 

y = np.ravel(y)

In [140]:
X.tail()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
253675,1,1,1,45,0,0,0,0,1,1,...,1,0,3,0,5,0,1,5,6,7
253676,1,1,1,18,0,0,0,0,0,0,...,1,0,4,0,0,1,0,11,2,4
253677,0,0,1,28,0,0,0,1,1,0,...,1,0,1,0,0,0,0,2,5,2
253678,1,0,1,23,0,0,0,0,1,1,...,1,0,3,0,0,0,1,7,5,1
253679,1,1,1,25,0,0,1,1,1,0,...,1,0,2,0,0,0,0,9,6,2

In [141]:
y

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

**3. Get the Statistical Details**

In [142]:
X.describe()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,...,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000
mean,0.429001,0.424121,0.962670,28.382364,0.443169,0.040571,0.094186,0.756544,0.634256,0.811420,...,0.951053,0.084177,2.511392,3.184772,4.242081,0.168224,0.440342,8.032119,5.050434,6.053875
std,0.494934,0.494210,0.189571,6.608694,0.496761,0.197294,0.292087,0.429169,0.481639,0.391175,...,0.215759,0.277654,1.068477,7.412847,8.717951,0.374066,0.496429,3.054220,0.985774,2.071148
min,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

# **2. Split Dataset into training and testing dataset**

In [143]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [144]:
import statsmodels.api as sm

# Use the statsmodels package to create and fit a linear regression

lr = sm.OLS(y_train, X_train).fit()

# Create a variable to hold the p-values of all columns sorted in ascending order

p_values = lr.pvalues.sort_values(ascending=True)
p_values

HighBP                   0.000000e+00
BMI                      0.000000e+00
GenHlth                  0.000000e+00
HighChol                1.705755e-286
HeartDiseaseorAttack    8.924879e-146
Education               1.103831e-102
DiffWalk                 2.079357e-88
Income                   1.185271e-68
HvyAlcoholConsump        2.980002e-61
Age                      3.238950e-56
PhysActivity             1.473836e-23
Smoker                   1.871152e-18
Sex                      7.427505e-16
NoDocbcCost              5.494107e-14
AnyHealthcare            1.637297e-13
MentHlth                 2.064598e-13
Stroke                   3.846337e-13
Veggies                  1.915071e-08
CholCheck                1.166111e-04
PhysHlth                 1.719561e-03
Fruits                   1.281848e-02
dtype: float64

In [145]:
X_train_df = pd.DataFrame(X_train, columns=X.columns)
X_test_df = pd.DataFrame(X_test, columns=X.columns)

X_train_df

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
253350,0,0,1,27,0,0,0,1,0,1,...,0,0,3,30,0,0,1,4,5,6
46849,1,1,1,28,1,0,0,1,0,1,...,1,0,3,0,0,0,1,12,6,8
108186,0,1,1,27,1,0,0,1,1,1,...,1,0,3,2,2,0,1,8,6,7
74790,0,0,1,29,0,0,0,1,1,1,...,1,0,2,0,0,0,1,8,5,8
193337,1,0,1,27,1,0,1,1,0,1,...,1,0,3,1,0,0,0,11,6,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176963,0,1,1,23,0,0,0,1,1,1,...,1,0,2,0,0,0,0,4,6,8
117952,0,0,1,27,0,0,0,1,1,1,...,1,0,1,0,0,0,1,6,5,8
173685,1,1,1,42,0,0,1,0,0,0,...,1,0,3,10,7,1,0,13,4,6
43567,1,1,1,27,1,0,1,1,1,1,...,1,0,3,0,5,0,1,12,5,7
199340,0,0,1,22,1,0,0,1,1,0,...,1,0,3,0,0,0,1,12,5,7

In [146]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train['BMI'] = scaler.fit_transform(X_train_df[['BMI']])
X_test['BMI'] = scaler.transform(X_test_df[['BMI']])

X_train['GenHlth'] = scaler.fit_transform(X_train_df[['GenHlth']])
X_test['GenHlth'] = scaler.transform(X_test_df[['GenHlth']])

X_train['MentHlth'] = scaler.fit_transform(X_train_df[['MentHlth']])
X_test['MentHlth'] = scaler.transform(X_test_df[['MentHlth']])

X_train['PhysHlth'] = scaler.fit_transform(X_train_df[['PhysHlth']])
X_test['PhysHlth'] = scaler.transform(X_test_df[['PhysHlth']])

X_train['Age'] = scaler.fit_transform(X_train_df[['Age']])
X_test['Age'] = scaler.transform(X_test_df[['Age']])

X_train['Education'] = scaler.fit_transform(X_train_df[['Education']])
X_test['Education'] = scaler.transform(X_test_df[['Education']])

X_train['Income'] = scaler.fit_transform(X_train_df[['Income']])
X_test['Income'] = scaler.transform(X_test_df[['Income']])

In [147]:
X_train = pd.DataFrame(X_train, columns=X.columns)
X_test = pd.DataFrame(X_test, columns=X.columns)

X_train

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
253350,0,0,1,-0.209156,0,0,0,1,0,1,...,0,0,0.459597,3.614009,-0.486791,0,1,-1.319063,-0.052411,-0.026896
46849,1,1,1,-0.058079,1,0,0,1,0,1,...,1,0,0.459597,-0.430646,-0.486791,0,1,1.301212,0.963302,0.939919
108186,0,1,1,-0.209156,1,0,0,1,1,1,...,1,0,0.459597,-0.161003,-0.257535,0,1,-0.008925,0.963302,0.456511
74790,0,0,1,0.092998,0,0,0,1,1,1,...,1,0,-0.477314,-0.430646,-0.486791,0,1,-0.008925,-0.052411,0.939919
193337,1,0,1,-0.209156,1,0,1,1,0,1,...,1,0,0.459597,-0.295824,-0.486791,0,0,0.973677,0.963302,0.939919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176963,0,1,1,-0.813464,0,0,0,1,1,1,...,1,0,-0.477314,-0.430646,-0.486791,0,0,-1.319063,0.963302,0.939919
117952,0,0,1,-0.209156,0,0,0,1,1,1,...,1,0,-1.414225,-0.430646,-0.486791,0,1,-0.663994,-0.052411,0.939919
173685,1,1,1,2.056999,0,0,1,0,0,0,...,1,0,0.459597,0.917572,0.315605,1,0,1.628746,-1.068125,-0.026896
43567,1,1,1,-0.209156,1,0,1,1,1,1,...,1,0,0.459597,-0.430646,0.086349,0,1,1.301212,-0.052411,0.456511
199340,0,0,1,-0.964541,1,0,0,1,1,0,...,1,0,0.459597,-0.430646,-0.486791,0,1,1.301212,-0.052411,0.456511

# **3. Model Selection**

## **3.1 Initialize Models**

Model 1: KNN

In [148]:
'''
# Loop through different k values to find which has the highest accuracy.
# Note: We use only odd numbers because we don't want any ties.
train_scores = []
test_scores = []

for k in range(1, 20, 2):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    train_score = knn.score(X_train, y_train)
    test_score = knn.score(X_test, y_test)
    train_scores.append(train_score)
    test_scores.append(test_score)
    print(f"k: {k}, Train/Test Score: {train_score:.3f}/{test_score:.3f}")
    
# Plot the results

plt.plot(range(1, 20, 2), train_scores, marker='o')
plt.plot(range(1, 20, 2), test_scores, marker="x")
plt.xlabel("k neighbors")
plt.ylabel("Testing accuracy Score")
plt.legend(["train", "test"])'
'''

'\n# Loop through different k values to find which has the highest accuracy.\n# Note: We use only odd numbers because we don\'t want any ties.\ntrain_scores = []\ntest_scores = []\n\nfor k in range(1, 20, 2):\n    knn = KNeighborsClassifier(n_neighbors=k)\n    knn.fit(X_train, y_train)\n    train_score = knn.score(X_train, y_train)\n    test_score = knn.score(X_test, y_test)\n    train_scores.append(train_score)\n    test_scores.append(test_score)\n    print(f"k: {k}, Train/Test Score: {train_score:.3f}/{test_score:.3f}")\n    \n# Plot the results\n\nplt.plot(range(1, 20, 2), train_scores, marker=\'o\')\nplt.plot(range(1, 20, 2), test_scores, marker="x")\nplt.xlabel("k neighbors")\nplt.ylabel("Testing accuracy Score")\nplt.legend(["train", "test"])\'\n'

Model 2: Decision Tree

In [149]:
model_DT = tree.DecisionTreeClassifier()

Model 3: Random Forest Classfier

In [150]:
model_RFC = RandomForestClassifier()

Model 4: Extremely Random Forest Classfier

In [151]:
model_ERT = ExtraTreesClassifier(random_state=1)

Model 5: Neural Networks

In [152]:
model_MLPC = MLPClassifier()

Model 6: Logistic Regression

In [153]:
model_LR = LogisticRegression( max_iter=1000)

Model 7: Support Vector Classifier

In [154]:
model_SVC = SVC(kernel='linear')

## **3.2 Train Models**

Model 1: KNN

In [155]:
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train, y_train)

KNeighborsClassifier()

Model 2: Decision Tree

In [156]:
model_DT.fit(X_train, y_train)

DecisionTreeClassifier()

Model 3: Random Forest Classifier

In [157]:
model_RFC.fit(X_train,y_train)

RandomForestClassifier()

Model 4: Extremely Random Forest Classifier

In [158]:
model_ERT.fit(X_train, y_train)

ExtraTreesClassifier(random_state=1)

Model 5: Neural Networks

In [159]:
model_MLPC.fit(X_train,y_train)

MLPClassifier()

Model 6: Logistic Regression

In [160]:
model_LR.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

Model 7: Support Vector Classifier

In [161]:
#model_SVC.fit(X_train, y_train)

## **3.3 Evaluate Models**

Model 1: KNN

In [162]:
y_knn = model_knn.predict(X_test)

Model 2: Decision Tree

In [163]:
y_DT = model_DT.predict(X_test)

Model 3: Random Forest Classifier

In [164]:
y_RFC = model_RFC.predict(X_test)

Model 4: Extremely Random Forest Classifier

In [165]:
y_ERT = model_ERT.predict(X_test)

Model 5: Neural Networks

In [166]:
y_MLPC = model_MLPC.predict(X_test)

Model 6: Logistics Regression

In [167]:
y_LR = model_LR.predict(X_test)

Model 7: Support Vector Classifier

y_SVC = model_SVC.predict(X_test)


## **3.4 Calcualte the Precision, Recall And Accuracy Score for our model**

Model 1: KNN

In [168]:
roc_auc_knn = metrics.roc_auc_score(y_test, y_knn)

print("KNN Performace Metrics")
print("\n")
print("Confusion Matrix")
print(confusion_matrix(y_test,y_knn))
print("\nClassification Report")
print(classification_report(y_test,y_knn))
print('ROC AUC:', round(roc_auc_knn*100,2),"%")

KNN Performace Metrics


Confusion Matrix
[[62287  3063]
 [ 8420  2334]]

Classification Report
              precision    recall  f1-score   support

           0       0.88      0.95      0.92     65350
           1       0.43      0.22      0.29     10754

    accuracy                           0.85     76104
   macro avg       0.66      0.59      0.60     76104
weighted avg       0.82      0.85      0.83     76104

ROC AUC: 58.51 %

Model 2: Decision Tree

In [169]:
roc_auc_DT = metrics.roc_auc_score(y_test, y_DT)

print("DT Performace Metrics")
print("\n")
print("Confusion Matrix")
print(confusion_matrix(y_test,y_DT))
print("\nClassification Report")
print(classification_report(y_test,y_DT))
print('ROC AUC:', round(roc_auc_DT*100,2),"%")

DT Performace Metrics


Confusion Matrix
[[57150  8200]
 [ 7238  3516]]

Classification Report
              precision    recall  f1-score   support

           0       0.89      0.87      0.88     65350
           1       0.30      0.33      0.31     10754

    accuracy                           0.80     76104
   macro avg       0.59      0.60      0.60     76104
weighted avg       0.80      0.80      0.80     76104

ROC AUC: 60.07 %

Model 3: Random Forest Classifier

In [170]:
roc_auc_RFC = metrics.roc_auc_score(y_test, y_RFC)

print("RFC Performace Metrics")
print("\n")
print("Confusion Matrix")
print(confusion_matrix(y_test,y_RFC))
print("\nClassification Report")
print(classification_report(y_test,y_RFC))
print('ROC AUC:', round(roc_auc_RFC*100,2),"%")

RFC Performace Metrics


Confusion Matrix
[[63562  1788]
 [ 8973  1781]]

Classification Report
              precision    recall  f1-score   support

           0       0.88      0.97      0.92     65350
           1       0.50      0.17      0.25     10754

    accuracy                           0.86     76104
   macro avg       0.69      0.57      0.59     76104
weighted avg       0.82      0.86      0.83     76104

ROC AUC: 56.91 %

Model 4: Extremely Random Forest Classifier

In [171]:
roc_auc_ERT = metrics.roc_auc_score(y_test, y_ERT)

print("ERT Performace Metrics")
print("\n")
print("Confusion Matrix")
print(confusion_matrix(y_test,y_ERT))
print("\nClassification Report")
print(classification_report(y_test,y_ERT))
print('ROC AUC:', round(roc_auc_ERT*100,2),"%")

ERT Performace Metrics


Confusion Matrix
[[62915  2435]
 [ 8865  1889]]

Classification Report
              precision    recall  f1-score   support

           0       0.88      0.96      0.92     65350
           1       0.44      0.18      0.25     10754

    accuracy                           0.85     76104
   macro avg       0.66      0.57      0.58     76104
weighted avg       0.81      0.85      0.82     76104

ROC AUC: 56.92 %

Model 5: Neural Networks

In [172]:
roc_auc_MPLC = metrics.roc_auc_score(y_test, y_MLPC)

print("MPLC Performace Metrics")
print("\n")
print("Confusion Matrix")
print(confusion_matrix(y_test,y_MLPC))
print("\nClassification Report")
print(classification_report(y_test,y_MLPC))
print('ROC AUC:', round(roc_auc_MPLC*100,2),"%")

MPLC Performace Metrics


Confusion Matrix
[[64260  1090]
 [ 9176  1578]]

Classification Report
              precision    recall  f1-score   support

           0       0.88      0.98      0.93     65350
           1       0.59      0.15      0.24     10754

    accuracy                           0.87     76104
   macro avg       0.73      0.57      0.58     76104
weighted avg       0.83      0.87      0.83     76104

ROC AUC: 56.5 %

Model 6: Logistics Regression

In [173]:
roc_auc_LR = metrics.roc_auc_score(y_test, y_LR)

print("LR Performace Metrics")
print("\n")
print("Confusion Matrix")
print(confusion_matrix(y_test,y_LR))
print("\nClassification Report")
print(classification_report(y_test,y_LR))
print('ROC AUC:', round(roc_auc_LR*100,2),"%")

LR Performace Metrics


Confusion Matrix
[[64054  1296]
 [ 9074  1680]]

Classification Report
              precision    recall  f1-score   support

           0       0.88      0.98      0.93     65350
           1       0.56      0.16      0.24     10754

    accuracy                           0.86     76104
   macro avg       0.72      0.57      0.58     76104
weighted avg       0.83      0.86      0.83     76104

ROC AUC: 56.82 %

# **4. Test the model Manuallly**

In [174]:
# Testing the Model

HighBP = 1
HighChol = 1
CholCheck = 1
BMI = 25
Smoker = 0
Stroke = 0
HeartDiseaseorAttack = 1
PhysActivity = 1
Fruits = 1
Veggies = 0
HvyAlcoholConsump = 0
AnyHealthcare = 1
NoDocbcCost = 0
GenHlth = 2
MentHlth = 0
PhysHlth = 0
DiffWalk = 0
Sex = 0
Age = 9
Education = 6
Income = 2

manual_pred_knn = model_knn.predict([[HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]])
manual_pred_DT = model_DT.predict([[HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]])
manual_pred_RFC = model_RFC.predict([[HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]])
manual_pred_ERT = model_ERT.predict([[HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]])
manual_pred_MLPC = model_MLPC.predict([[HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]])
manual_pred_LR = model_LR.predict([[HighBP, HighChol, CholCheck, BMI, Smoker, Stroke
                                    , HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]]) 

print('KNN Prediction:', manual_pred_knn)
print('DT Prediction:', manual_pred_DT)
print('RFC Prediction:', manual_pred_RFC)
print('ERT Prediction:', manual_pred_ERT)
print('MLPC Prediction:', manual_pred_MLPC)
print('LR Prediction:', manual_pred_LR)

KNN Prediction: [0]
DT Prediction: [1]
RFC Prediction: [1]
ERT Prediction: [1]
MLPC Prediction: [0]
LR Prediction: [1]

c:\Users\Afiat_Trading\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
c:\Users\Afiat_Trading\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\Afiat_Trading\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\Afiat_Trading\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(
c:\Users\Afiat_Trading\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(
c:\Users\Afiat_Trading\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

# **5. Save Model**

#### **4.1 KNN Model**

In [175]:
joblib.dump(model_knn, 'model_knn.joblib')

['model_knn.joblib']

#### **4.2 Decision Tree Model**

In [176]:
joblib.dump(model_DT, 'model_DT.joblib')

['model_DT.joblib']

#### **4.3 Random Forest Tree Model**

In [177]:
joblib.dump(model_RFC, 'model_RFC.joblib')

['model_RFC.joblib']

#### **4.4 Extremely Random Forest Tree Model**

In [178]:
joblib.dump(model_ERT, 'model_ERT.joblib')

['model_ERT.joblib']

#### **4.5 Neural Networks Model**

In [179]:
joblib.dump(model_MLPC, 'model_MLPC.joblib')

['model_MLPC.joblib']

# **6. Load the Model**

#### **5.1 KNN Model**

In [180]:
pickle.dump(model_knn, open('model_knn.sav','wb'))
model_knn = pickle.load(open('model_knn.sav','rb'))

#### **5.2 Decision Tree Model**

In [181]:
pickle.dump(model_DT, open('model_DT.sav','wb'))
model_DT = pickle.load(open('model_DT.sav','rb'))

#### **5.3 Random Forest Tree Model**

In [182]:
pickle.dump(model_RFC, open('model_RFC.sav','wb'))
model_RFC = pickle.load(open('model_RFC.sav','rb'))

#### **5.4 Extremely Random Forest Tree Model**

In [183]:
pickle.dump(model_ERT, open('model_ERT.sav','wb'))
model_ERT = pickle.load(open('model_ERT.sav','rb'))

#### **5.5 Neural Networks Model**

In [184]:
pickle.dump(model_MLPC, open('model_MLPC.sav','wb'))
model_MLPC = pickle.load(open('model_MLPC.sav','rb'))

# **7. Test the Models**

In [185]:
HighBP = 1
HighChol = 1
CholCheck = 1
BMI = 25
Smoker = 0
Stroke = 0
HeartDiseaseorAttack = 1
PhysActivity = 1
Fruits = 1
Veggies = 0
HvyAlcoholConsump = 0
AnyHealthcare = 1
NoDocbcCost = 0
GenHlth = 2
MentHlth = 0
PhysHlth = 0
DiffWalk = 0
Sex = 0
Age = 9
Education = 6
Income = 2

In [186]:
manual_pred_knn = model_knn.predict([[HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]])
manual_pred_DT = model_DT.predict([[HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]])
manual_pred_RFC = model_RFC.predict([[HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]])
manual_pred_ERT = model_ERT.predict([[HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]])
manual_pred_MLPC = model_MLPC.predict([[HighBP, HighChol, CholCheck, BMI, Smoker, Stroke, HeartDiseaseorAttack, PhysActivity, Fruits, Veggies, HvyAlcoholConsump, AnyHealthcare, NoDocbcCost, GenHlth, MentHlth, PhysHlth, DiffWalk, Sex, Age, Education, Income]])    
                                      
print('KNN Prediction:', manual_pred_knn)
print('DT Prediction:', manual_pred_DT)
print('RFC Prediction:', manual_pred_RFC)
print('ERT Prediction:', manual_pred_ERT)
print('MLPC Prediction:', manual_pred_MLPC)

KNN Prediction: [0]
DT Prediction: [1]
RFC Prediction: [1]
ERT Prediction: [1]
MLPC Prediction: [0]

c:\Users\Afiat_Trading\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
c:\Users\Afiat_Trading\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
c:\Users\Afiat_Trading\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\Afiat_Trading\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but ExtraTreesClassifier was fitted with feature names
  warnings.warn(
c:\Users\Afiat_Trading\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(